// ============================================================================
// npu_addrmap_pkg.sv - MMIO register / buffer address map
//   AUTO-GENERATED by tools/gen/gen_addrmap.py - do not edit by hand
// ============================================================================

package npu_addrmap_pkg;

    import npu_types_pkg::*;

    // Register offsets (MMIO byte addresses)
    localparam logic [MMIO_ADDR_W-1:0] REG_CTRL         = 20'h0_0000;
    localparam logic [MMIO_ADDR_W-1:0] REG_STATUS       = 20'h0_0004;
    localparam logic [MMIO_ADDR_W-1:0] REG_DOORBELL     = 20'h0_0008;
    localparam logic [MMIO_ADDR_W-1:0] REG_IRQ_STATUS   = 20'h0_000C;
    localparam logic [MMIO_ADDR_W-1:0] REG_IRQ_ENABLE   = 20'h0_0010;
    localparam logic [MMIO_ADDR_W-1:0] REG_IRQ_CLEAR    = 20'h0_0014;
    localparam logic [MMIO_ADDR_W-1:0] REG_FEATURE_ID   = 20'h0_0018;
    localparam logic [MMIO_ADDR_W-1:0] REG_PERF_CYCLES  = 20'h0_0020;
    localparam logic [MMIO_ADDR_W-1:0] REG_PERF_ACTIVE  = 20'h0_0024;
    localparam logic [MMIO_ADDR_W-1:0] REG_PERF_STALL   = 20'h0_0028;

    // Command queue window
    localparam logic [MMIO_ADDR_W-1:0] CMD_QUEUE_BASE   = 20'h0_1000;
    localparam int                     CMD_ENTRY_BYTES  = 64;

    // Buffer windows
    localparam logic [MMIO_ADDR_W-1:0] WEIGHT_BUF_BASE  = 20'h1_0000;
    localparam logic [MMIO_ADDR_W-1:0] ACT_BUF_BASE     = 20'h2_0000;
    localparam logic [MMIO_ADDR_W-1:0] PSUM_BUF_BASE    = 20'h3_0000;

    // Control register bit fields
    localparam int CTRL_SOFT_RESET_BIT                  = 0;
    localparam int CTRL_ENABLE_BIT                      = 1;

    // Status register bit fields
    localparam int STATUS_IDLE_BIT                      = 0;
    localparam int STATUS_BUSY_BIT                      = 1;
    localparam int STATUS_QUEUE_FULL                    = 2;

endpackage : npu_addrmap_pkg
