/* npu_regs.h - NPU register map (auto-generated by gen_headers.py) */

#ifndef _LGNPU_REGS_H
#define _LGNPU_REGS_H

#include <stdint.h>

/* Register offsets */
#define LGNPU_REG_CTRL                 0x00000U
#define LGNPU_REG_STATUS               0x00004U
#define LGNPU_REG_DOORBELL             0x00008U
#define LGNPU_REG_IRQ_STATUS           0x0000CU
#define LGNPU_REG_IRQ_ENABLE           0x00010U
#define LGNPU_REG_IRQ_CLEAR            0x00014U
#define LGNPU_REG_FEATURE_ID           0x00018U
#define LGNPU_REG_PERF_CYCLES          0x00020U
#define LGNPU_REG_PERF_ACTIVE          0x00024U
#define LGNPU_REG_PERF_STALL           0x00028U

/* DMA engine registers */
#define LGNPU_REG_DMA_EXT_ADDR         0x00030U
#define LGNPU_REG_DMA_LOC_ADDR         0x00034U
#define LGNPU_REG_DMA_LEN              0x00038U
#define LGNPU_REG_DMA_CTRL             0x0003CU
#define LGNPU_REG_DMA_STATUS           0x00040U

/* Buffer / queue bases */
#define LGNPU_CMD_QUEUE_BASE           0x01000U
#define LGNPU_WEIGHT_BUF_BASE          0x10000U
#define LGNPU_ACT_BUF_BASE             0x20000U
#define LGNPU_PSUM_BUF_BASE            0x30000U
#define LGNPU_CMD_ENTRY_BYTES          64U

/* CTRL register bits */
#define LGNPU_CTRL_SOFT_RESET          (1U << 0)
#define LGNPU_CTRL_ENABLE              (1U << 1)

/* STATUS register bits */
#define LGNPU_STATUS_IDLE              (1U << 0)
#define LGNPU_STATUS_BUSY              (1U << 1)
#define LGNPU_STATUS_QUEUE_FULL        (1U << 2)

/* DMA control register bits */
#define LGNPU_DMA_CTRL_START           (1U << 0)
#define LGNPU_DMA_CTRL_DIR             (1U << 1)  /* 0 = ext->local, 1 = local->ext */

/* DMA status register bits */
#define LGNPU_DMA_STATUS_BUSY          (1U << 0)

#endif /* _LGNPU_REGS_H */
