/* npu_regs.h - NPU register map (auto-generated by gen_headers.py) */

#ifndef NPU_REGS_H
#define NPU_REGS_H

#include <stdint.h>

/* Register offsets */
#define NPU_REG_CTRL                 0x00000U
#define NPU_REG_STATUS               0x00004U
#define NPU_REG_DOORBELL             0x00008U
#define NPU_REG_IRQ_STATUS           0x0000CU
#define NPU_REG_IRQ_ENABLE           0x00010U
#define NPU_REG_IRQ_CLEAR            0x00014U
#define NPU_REG_FEATURE_ID           0x00018U
#define NPU_REG_PERF_CYCLES          0x00020U
#define NPU_REG_PERF_ACTIVE          0x00024U
#define NPU_REG_PERF_STALL           0x00028U

/* DMA engine registers */
#define NPU_REG_DMA_EXT_ADDR         0x00030U
#define NPU_REG_DMA_LOC_ADDR         0x00034U
#define NPU_REG_DMA_LEN              0x00038U
#define NPU_REG_DMA_CTRL             0x0003CU
#define NPU_REG_DMA_STATUS           0x00040U

/* Buffer / queue bases */
#define NPU_CMD_QUEUE_BASE           0x01000U
#define NPU_WEIGHT_BUF_BASE          0x10000U
#define NPU_ACT_BUF_BASE             0x20000U
#define NPU_PSUM_BUF_BASE            0x30000U
#define NPU_CMD_ENTRY_BYTES          64U

/* CTRL register bits */
#define NPU_CTRL_SOFT_RESET          (1U << 0)
#define NPU_CTRL_ENABLE              (1U << 1)

/* STATUS register bits */
#define NPU_STATUS_IDLE              (1U << 0)
#define NPU_STATUS_BUSY              (1U << 1)
#define NPU_STATUS_QUEUE_FULL        (1U << 2)

/* DMA control register bits */
#define NPU_DMA_CTRL_START           (1U << 0)
#define NPU_DMA_CTRL_DIR             (1U << 1)  /* 0 = ext->local, 1 = local->ext */

/* DMA status register bits */
#define NPU_DMA_STATUS_BUSY          (1U << 0)

#endif /* NPU_REGS_H */
